mysql:
    restart: always
    image: mysql:5.7
    ports:
        - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: node_app
        MYSQL_PASSWORD: root
    volumes:
      - /data/mysql:/var/lib/mysql
app:
    build: ./app
    tty: true
    links:
        - mysql
    ports:
        - 5000
    volumes:
        - ./app/:/usr/src/app/
        - ./logs/node_app/:/var/log/node_app/
nginx:
    image: nginx:1.10.0-alpine
    ports:
        - 8999:8080
    links:
        - app
    volumes:
        - ./logs/nginx/:/var/log/nginx/
        - ./nginx/:/etc/nginx/conf.d/
